import './globals.css'
import Header from './component/Header'
import Navbar from './component/Navbar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <Header />
          {/* <Navbar /> */}
          <Navbar />
          {children}
      </body>
    </html>
  )
}
